### ISSUE TITLE
changeing race in character creator problems

### ISSUE THREAD

**Issue by IndirectCell** [sojourn-13/sojourn-station#1857]
![bilde](https://user-images.githubusercontent.com/60559077/132054110-f0284c5e-8359-4853-947a-63926af5d7b9.png)

Trows up a ton of errors, i was switching between races, wouldnt let me change job or whatever the error seemed to suggest i needed to change.

**Comment by r4d6** [comment]
Yeah, we don't use Github's issue tracker.
But the error is probably a soteria/blackshield prosthetic. The reason it happen so often is because it happen every time you change a thing.

**Comment by IndirectCell** [comment]
that was from one click, it keep happening while i was spectating, i got disconnected in end and just gave up.

**Comment by IndirectCell** [comment]
probably a good idea removeing the link from within game to the bugtracker used :x

**Comment by Kazkin** [comment]
The issue is caused by not having any department for your base organs as even setting base organs to all departments causes the game to go "no department means no match" thus the error and the many repetitions.
