### ISSUE TITLE
[SUGGESTION] Blackshield uniform changes.

### ISSUE THREAD

**Issue by EliteRiceFarmer** [sojourn-13/sojourn-station#2429]
Right. The last PR was chaotic. Let's get a few things discussed before I try another attempt.

Let's go by opinions of Blackshield players first. Then we'll get to the leadership's opinions, let's get started.

Q: Do you want any form of rank representation?
A: No, but shoulderboard should be added to dress uniform box.

Q: Do you want the uniform in locker to be set to one colour?
A: Yes. Blackshield should be black/grey as their standard.

Q: Do you want uniform varieties?
A: Yes, but put it behind a vendor operated by the Sergeant. So Sergeant can issue out special uniforms when the situation requires.

Q: Do you prefer the new fatigue made by Trilby or the old Gorkas?
A: If it's like you said, then you can change to fatigue. It's more modular than the Gorkas and should completely replace Gorkas for Blackshield.

Q: Would you like stuff to be organised into small boxes instead of a pile of mess in the locker?
A: A box with the uniform: Shoes, fatigue, boots, a box with accessories: Rig, holster and a box with tools: Knife and tomahawk.

Q: Last question. What's varieties would you want in the future?
A: Fatigue skirt. Please.

Opinions are provided by: Cryleve#2325, Pedro9000#6451, PortuGoose#8032, MoJlodoY#0149, Мяу!#0979, CDB#3485, Archduke Polyushko#0323, Sha ⚜#9155.

Now onto the leadership's opinion that I got throughout the discussion in both DM and #Player_staff_talk:

Sieghardt - Fleshbound#3710:
Late but true: We do not want Blackshield to be anything like milRP. It already went through that phase and was denied.
A - 
I've been playing Blackshield for nearly two years now. I know the MilRP phase and it was horrible. You don't have to worry about it cause I know what I'm doing. Trust is important.

Christmas Possum (Kaz) - Possum#2853
Just to be clear, is the idea that you want to put all the custom stuff aside in its own, still accessible, locker and put just a single uniform color in the starting lockers?
A -
Yes. but like the opinion provided by the players above. It would be put behind a vendor and operated by the Sergeant to enforce uniform code. Right now varieties without enforcement is just Scavs with extra step. Blackshield is basically Scavs but somehow less effective. Even Scavs has dress code.

XVIII The Moon - CDB#3485
There is a uniform code. It just isn't really enforced by commanders and sergeants.
A -
I know this so in order to make it more effective. We need to give them the tools to do that in roleplay. Currently, a lot of sergeants and commanders has told me. That's enforcing it is impossible cause "It's in the locker, So I can wear it." argument. I've enforce said code for ages and I've met numerous people arguing with said words.

Trilby - Trilby#4809
Keep options. Do not remove them from locker.
A -
I'm not removing them. Though albeit would delete the gorkas if the changes are allowed.
I'm making them less accessible, not inaccessible. By making them vendor-only or Sergeant controlled. Allowing for a more uniformed style than "I wear what I want" situation.

Right, now onto the changes I propose:

1 - Replace Gorkas with the Fatigues made by Trilby, as well create a source path for the fatigue to deal with the "fiber" problem. Getting spriters (I can hire them.) to finalise the variants provided using adjust style.

2 - Sorting all the uniforms in sergeant, commander, trooper and corpsman locker into boxes instead of a pile of stuff. This would make a cleaner secure closet.

3 - All unsecure lockers such as accessories and spare uniforms will be filled with only standard issued black/grey colour fatigues.

4 - New vendor that can dispense spare uniforms in other colours such as Tan, green at the disposal of the Sergeant instead of
free for all access.

5 - Removing the duplicate Boltgun in the trooper's secure closet to prevent having two pistol and two mosin. Making the voucher redundant.

6 - Creating new path for the Fatigues so it's not overlapping with map-spawned fatigues. (Would need a mapper to check on this. If it doesn't spawn on the map or any unsecure lockers. Then this proposal would be ingored.)

7 - Buffing the commander and Sergeant saber damage to 20-30 cause it's currently 10 while the boot knife is 26.

8 - Hire a spriter to fully complete variants of the plate carrier, flak plate carrier and commander's plate in three patterns:
Tan, green and black for Blackshield. Same application to the fatigue, with three seperate fatigue in the following colour: tan, green black offering alt-styles in: Short sleeve, pants only and corpsman.

in total, if calculate correctly.
There will be three main fatigue paths, then seperate into three alt-style paths.
Would need total of 9 sprites. Excluding skirt options.

The helmet and armours would require total of
3 for the helmet.
6 for the normal plate carrier and it upgraded version.
6 for the flak plate carrier and it upgraded version.
3 for the the commander's overcoat/plate carrier.

EDIT:
Can I add a WW1 whistle too?

**Comment by EliteRiceFarmer** [comment]
For clarification: I can code and sprite.

Please give comments on thoughts, Then I'll make a PR.

**Comment by r4d6** [comment]
Why not use the kit vendor that's already there?

**Comment by EliteRiceFarmer** [comment]
> Why not use the kit vendor that's already there?

I'm seeking a full change than just that simple system. To be honest.

Minor changes don't create progress.
You need to do something decisive to make the experience better.

Also, the kit vendor is extremely volatile at best and redundant at worse.

They still spawn with full armour and equipment in their locker as well weapons. What's the purpose of the vendor other than being an alternative, redundant addition without any proper changes?

**Comment by r4d6** [comment]
> > Why not use the kit vendor that's already there?
> 
> I'm seeking a full change than just that simple system. To be honest.
> 
> Minor changes don't create progress. You need to do something decisive to make the experience better.
> 
> Also, the kit vendor is extremely volatile at best and redundant at worse.
> 
> They still spawn with full armour and equipment in their locker as well weapons. What's the purpose of the vendor other than being an alternative, redundant addition without any proper changes?

... I thought I removed those from the lockers. At the very least I removed the weapons.

**Comment by r4d6** [comment]
https://github.com/sojourn-13/sojourn-station/blob/master/code/game/objects/structures/crates_lockers/closets/secure/militia.dm#L90

Their lockers do _**NOT**_ start with _**ANY**_ weapons or armor. The hell are you on about?

**Comment by cdb-is-not-good** [comment]
Im gonna mostly be rehashing what i said on the last PR. The consensus last time this was discussed was MilRP bad, and reducing player choice in appearance=bad. 
>"okay what if we gate uniforms behind a 500$ fee that no one will pay"
>"what if only the sergeant can get them so they get to chose!"
These are all pretty transparent attempts to just bypass the overall idea that forcing the shield to all look exactly the same is lame, and it's definitely not the shields biggest problem- or even really much of a problem?
Sergeants and Commanders HAVE the tools, but as is often the case enforcement requires giving orders and demanding things of your staff - which puts you often in the position of having to explain yourself or else start losing face.

**Comment by EliteRiceFarmer** [comment]
> https://github.com/sojourn-13/sojourn-station/blob/master/code/game/objects/structures/crates_lockers/closets/secure/militia.dm#L90
> 
> Their lockers do _**NOT**_ start with _**ANY**_ weapons or armor. The hell are you on about? Also, how is it volatile? it literally sell boxes.

![Uploading Screenshot_2021-12-10-09-00-59-31.jpg…]()

**Comment by EliteRiceFarmer** [comment]
> Im gonna mostly be rehashing what i said on the last PR. The consensus last time this was discussed was MilRP bad, and reducing player choice in appearance=bad.
> 
> > "okay what if we gate uniforms behind a 500$ fee that no one will pay"
> > "what if only the sergeant can get them so they get to chose!"
> 
> These are all pretty transparent attempts to just bypass the overall idea that forcing the shield to all look exactly the same is lame, and it's definitely not the shields biggest problem- or even really much of a problem? Sergeants and Commanders HAVE the tools, but as is often the case enforcement requires giving orders and demanding things of your staff - which puts you often in the position of having to explain yourself or else start losing face.

You're sidetracking the suggestion to IC issues but sure.

I can fully enforce a dress code as a Sergeant, I can explain the reasons why, which are numerous.

"The fuck are you? Clown?"
"We're Blackshield, not scavs. Wear the same fit or get the fuck out."
"You look like you just came out of a garbage pile, get into the fit or you're benched."

Etcetra.
Does it make some people hate me? Yes.
Does it make roleplay better? Absolutely.

Having the same uniform make me waste less times on having to read their name and more times on killing stuff while coordinating combat situation.

But if you prefer bad gameplay over player freedom, then sure. God forbid how many times I have to look at scavs and then Blackshield to tell who is who.

**Comment by cdb-is-not-good** [comment]
> You're sidetracking the suggestion to IC issues but sure.

Because they ARE IC issues chief, and they should be handled IC.

>While I do that all the time, what about other people who play leadership? Exactly. Giving them the tools to do so without having me around is much better alternative.

"other people don't do things how i do so i want to enforce my way of things mechanically."
Bruh.  They have the tools, how/if they chose to use them is their decision.

**Comment by DiscordWizard** [comment]
I'm not the most active player around but from what I've seen playing as sergeant and trooper, there's not much of an issue with uniforms currently. SOP already states that, as long as it's green/black/grey, identifiable as blackshield and proper, you can wear it. Hell I have my Sergeant work in camo pants because it fits that description while wearing everything else as standard from his locker.

I don't think it would be a good idea to restrict player choice on what they can or can't wear that much through vendor and access restrictions, it's the Sergeant's and Commander's job to deal with it IC if some trooper decides to wear pink and bright yellow as their uniform. You're basically their boss in a uniformed militia, tell them to act and dress like mature people or get out of blackshield.
