### ISSUE TITLE
[BUG] Dropping carts in maintenance mode makes them invisible

### ISSUE THREAD

**Issue by DiscordWizard** [sojourn-13/sojourn-station#2635]
After loading carts or lockers into a mech using a mech mounted clamp, if you leave it, go into maintenance mode and then deploy the wheelies to drag it around, if someone is inside and drops the carts/lockers they will be made forever invisible.

Not sure if it happens with all mechs but it was done with a Durand using a KILL CLAMP when this happened, with 3 carts and 1 medical locker inside its storage

**Comment by MicroMinty** [comment]
it happens with ripleys too!

**Comment by r4d6** [comment]
I just tested it on the live server, and the trash cart wasn't made invisible.

**Comment by Trilbyspaceclone** [comment]
This bug does infact happen when moving bettewn z-levels.

**Comment by Spoopy11** [comment]
Just happened to me.  Put cart in death Ripley.  Maintenance mode dragged it out of Haven.  Unloaded an invisible cart.
