### ISSUE TITLE
[MISSPLACEMENT] STS Blackshield para voucher gives the wrong ammunition type

### ISSUE THREAD

**Issue by DiscordWizard** [sojourn-13/sojourn-station#2636]
When you use the STS PARA voucher on the Blackshield Kit Vendor it gets you the gun but the short carbine magazines are all .257 magazines. None of them will fit or work with the STS, so you essentially get a weapon and useless magazines as your kit

**Comment by r4d6** [comment]
Did you even check the PRs ?
https://github.com/sojourn-13/sojourn-station/pull/2634

**Comment by DiscordWizard** [comment]
Swear to god there wasn't a [1] notification on PRs when I did this
Please don't smite me

**Comment by r4d6** [comment]
Alright, the PR to fix this issue is merged, please close this issue as soon as you can confirm it is fixed.
