### ISSUE TITLE
[Suggestion] Shaman path

### ISSUE THREAD

**Issue by Noobetski** [sojourn-13/sojourn-station#3073]
Not sure if anyone would ever see this, but i have idea for Absolute shaman path.
Shamans see absolute as greater spirit/keeper of nature, and to reach him/her/them, you must merge with nature by drinking from rivers, growing plants with natural dirt, feel absolute through forest and help jungle cycle continue. Spiders, roaches and other mutants are considered abominations, as they're corrupted by metal they live in, recycled air they breathe, artifical trash they eat, and must be given a redemption in order to stop their spirit's torture.
It must be noted that tehnology that turns life in what we see in maintenance (e.g. factories, polluting rivers, genemod facilities that destroy precious genome we were born with) is considered evil, as it corrupts what Absolute gave us, Tehnology that allows life to thrive is considered holy (e.g. Eco-farms, water recycling facilities, pollution filter).

Some possible cruciform litanies:
Peace of spirit: Makes you neutral to jungle mobs (birds, pigs, leapers, etc)
Touch of nature: Allows you to tame one small animal (leapers, diyaab, etc)
Spirit mercy: Disorients maint mobs for some time (lore-wise you _separate_ their spirit partially)
Blessing of forest: Upgraded plant growth litany.
Return to source: clears any unnatural mutations (obviously doesn't changes organs)

I'm not a coder, that's why it's an issue report and not PR.

**Comment by Noobetski** [comment]
It's just a concept/idea, so feel free to change one thing or another

**Comment by Trilbyspaceclone** [comment]
Internal talking has lead to this idea not being worked on.
If someone codes it or works on it go ahead otherwise this is a closed suggestion
