### ISSUE TITLE
Latex Maid alt state broken

### ISSUE THREAD

**Issue by elgeonmb** [sojourn-13/sojourn-station#3091]
PR 3080 added an alt style for the latex maid dress. however, the verb only updates icon_state, which is the in-inventory sprite, and not item_state, which is the on-mob sprite. this is bad!

also the relevant verb has a typo, which I wouldn't bother opening an issue for usually but if you're changing that code anyway might as well fix it.

**Comment by ThePainkiller** [comment]
Thank you for this report, I'll see if I can get that fixed.
