### ISSUE TITLE
Enviro Mask Style Bugged

### ISSUE THREAD

**Issue by Max-023** [sojourn-13/sojourn-station#3193]
The enviro mask has the adjust style feature just like it's parent, the base mask. Though, after adjusting the style in a round I found that returning the enviro mask to the base style does _not_ return it to the enviro mask sprite, and instead the parent base sprite.

I'd recommend checking the other masks that are children of the base mask to see if they have the same issue.

Steps to reproduce:
-Take enviro mask
-Adjust it's style to either kriosan or alternative
-Try to adjust it back and get the generic mask sprite
-Cry because the aesthetic is now lost

**Comment by ThePainkiller** [comment]
Going to get this checked and see if I can fix it. Most `adjust_style` verbs are very dumb on what slot they take (why the hell are jumpsuits `slot_back_str` and not `slot_w_uniform_str` ???) to update their icon and item states so I'm pretty sure the issue lies there.
