### ISSUE TITLE
Ranger Primary Weapon Armstrong Selection is an empty box.

### ISSUE THREAD

**Issue by MichaelMaCleod007** [sojourn-13/sojourn-station#3341]
Thankfully it was round end when I decided to try this with my voucher. Got an empty box devoid of gun or ammo. I found an Armstrong in the cryo item storage and took it thinking the other Ranger had cryoed out with it and was curious to see if it came with lethal ammo or just rubbers like the Judge does and found it to be bugged.

**Comment by SouthyOsmanli** [comment]
Might be an issue with vouchers in general, code wise I cannot see why only the Ranger one does this.

Also, funny thing I've noticed - after one person reports it in a round, no other rangers seem to have the issue for the rest of it. I THINK it has something to do with initalizing it or something. Very strange.

**Comment by Trilbyspaceclone** [comment]
unable to replicate

**Comment by Trilbyspaceclone** [comment]
Able to replicate, making fix soon
