### ISSUE TITLE
Ranged Mobs Attack Too Frequently

### ISSUE THREAD

**Issue by BurpleBineapple** [sojourn-13/sojourn-station#3438]
Issue stems from #3433 

Currently, ranged mobs are attacking too frequently due to an oversight in Nikotheguydude's PR. From what I can tell, the issue is quite simple:

![image](https://user-images.githubusercontent.com/67706292/170713708-d38139c0-d988-4c3d-bc71-79820f364bb0.png)

The new proc that has been added, shown above. This was originally three separate checks outside of a proc. There's a very major issue with merging movement and attacking procs into a single operation.

![image](https://user-images.githubusercontent.com/67706292/170713917-3156e8b8-1264-4ef6-824b-cbce934336c6.png)

The changes as you can see above, the new proc is called three times back to back. Because this proc handles movement, hostile checks, and attacking all at once, mobs are able to attack 3 times back to back. In particular, ranged mobs are able to very rapidly fire their weapon.

Two ways to fix this:

- Revert the PR entirely.
- Separate movement and attacking into two separate procs and apply appropriate delays for attacks. This way, mob aggression will be higher without increasing their attacks.

**Comment by nikothedude** [comment]
Not how this works, the switch ends after a condition is found true, meaning any operations in another case wont execute. The proc is ran once only per tick.

**Comment by Trilbyspaceclone** [comment]
The problem here is not a bug, and the code here that niko made isnt douping attacks.
Delays are being added tho.
