### ISSUE TITLE
Bunch of Guild related issues

### ISSUE THREAD

**Issue by Dissentbay** [sojourn-13/sojourn-station#3678]
<img width="101" alt="pipe" src="https://user-images.githubusercontent.com/4554200/179359122-106e8761-fcf8-4ab2-bd7f-e546ee76841d.png">
those pipes are either unable to be wrenched down (junction still works) or has extra steps that the average Guild member is unable to discover.

- [ ] 

<img width="169" alt="ammo" src="https://user-images.githubusercontent.com/4554200/179359208-ffe8712b-8d03-4d69-a32c-37905150d746.png">
both linked HP boxes print in HV (not slap, HV).

- [ x] 

<img width="261" alt="lean tcomms" src="https://user-images.githubusercontent.com/4554200/179359293-1874fe21-654a-4666-a9d9-b146c586dae3.png">
tcomms machinery uses 0 power

- [ ]

**Comment by Trilbyspaceclone** [comment]
Bottom most one is accully a issue of mapping as theirs 2 apcs

**Comment by Dissentbay** [comment]
the issue with tcomms not using power was an APC UI error, fixed when it got changed to TGUI
only the heat exchange pipe issue repains

**Comment by Trilbyspaceclone** [comment]
All issues have been (as far as im aware) been fixed or addressed
