### ISSUE TITLE
Psi armor steals cog

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#3717]
Been a issue driving me nuts for a long time and after being reported more then once never got fix. 

Gonna run though all the crap I was asked last time I reported this.

Yes I am aware psi armor grants you a tempt cog boost and would remove said boost after taking it off.
I am 100% sure without fail this is a issue I've seen it every single time I have used the armor.

The issue: The armor after removal will take away more cog then it boosted leaving you robbed of stats. Even if this is intended (I hope not) It's already a 4 essence cost plenty of a drawback as far as I see it. Robbing you of stats is very uncool moreso since forcing someone to grind stats is kinda meh. Some just wanna exist and not worry about that stuff.

As far as I'm aware this has been a issue since psionics was added.

**Comment by Trilbyspaceclone** [comment]
Unable to replicate issue with a BST

**Comment by benj8560** [comment]
Very strange I seen it just the other day. I'll make a effort to show you next chance I get but I really can't imagine such an issue being character specific

**Comment by benj8560** [comment]
right so turns out the issue was my reflex dropping the armor before it disappears screws up the way it works. I'd still argue its sorta a issue it works like that but I'll close it anyways since it no longer effects me now knowing how to handle it. Perhaps a little blurb in the examine text explaining somehow that is worth doing.

**Comment by Trilbyspaceclone** [comment]
Not sloved
