### ISSUE TITLE
Still very lacking nice RIG backpacks for us RIG enjoyers 

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#3741]
A few RIGs off the top of my head are still lacking true backpack on body sprites frankly ruining the look of the rest of the suit and hurting those who want style with their suits. Still retaining the default strapped up backpack sprite that covers 70% of your chest ruining a otherwise nice RIG sprite.

Blackshield RIG (looks so cool so sad ;-;), and Advance AMI (why tho? It's just a repainted rescue RIG the one it's copied from does not have this issue) and Trauma Team RIG.

Might have 1 more I forgot I'll update this if I see it but these are easily the most common ones if I can't remember any others.

Edit: New church rig sprite also has this issue it looks very cool but the big goofy grey backpack makes it so I can't even tell what the hell I'm looking at

**Comment by cdb-is-not-good** [comment]
Advanced AMI rig has one, actually. 
I started work to put something together for the shield suit using the ERT rig back item as its base(which its icon uses anyhow), just needs to be done in the proper blue-grey palette so it doesn't stand out as an all black backpack versus the suits tone.
Additionally I reached out to the Hussar suits creator to get them to fill in the missing sprite for their suits module

**Comment by benj8560** [comment]
advanced AMI I could have sworn I seen just the other day with the nasty default backpack and I know without a doubt it had it for some time. Unless this was just recently corrected that can't be right.

**Comment by benj8560** [comment]
![dreamseeker_H0OFF4rLJV](https://user-images.githubusercontent.com/26511091/182771402-7686e4a5-7509-471b-ba27-9c0870eff7ae.png)

Proof of such (thanks for posing Asil)

**Comment by cdb-is-not-good** [comment]
That's not the advanced AMI

**Comment by cdb-is-not-good** [comment]
I stand corrected actually! Anyway, working on a fix for the shield/advanced AMI via coder sprites

**Comment by Trilbyspaceclone** [comment]
This was handled in a CDB pr, if the case is still an issue please re-open a new issue
