### ISSUE TITLE
Soteria combat positronic implant very broken

### ISSUE THREAD

**Issue by ChefDoggo** [sojourn-13/sojourn-station#3775]
the implant given to the combat positronic ethnicity will only activate about 3ish times before refusing to activate through any means. removing the implant and readding it won't fix it either, in terms of recreation you just gotta spawn as one and activate it a bit then wait. after a bit it should just refuse to activate completely

**Comment by benj8560** [comment]
still applies to a implanted energy blade as well not just the synth round start one. Rather sure I've had it happen once or twice just getting one put in in round
