### ISSUE TITLE
Inflatables don't appear to be functioning.

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#3780]
Had inflatables just 100% not work on me making my life a nightmare. I did however have them work just fine maybe a week and a half ago. Unsure if they have only just broke or have become only somewhat functioning. Happened with stupidly high pressure from the nitrogen tank but worked fine some time ago with just a plasma issue.

**Comment by Trilbyspaceclone** [comment]
Found issue and is fixing with help with Niko
