### ISSUE TITLE
mobs are hesitant to walk over corpses and have bad pathing. 

### ISSUE THREAD

**Issue by ApplePlastic** [sojourn-13/sojourn-station#3839]
I'm not entirely sure if this affects other mobs as well, but from recent updates, both of the mobs listed in the title don't properly attack like they're supposed to, generally walking around corpses and moving out of sight of the player to attempt to find a new way to reach them. 

This happens less if there isn't any corpses of the same mob type present when they're aggro'd.

**Comment by ApplePlastic** [comment]
-haven't had time to actually attach a video of this happening, i'll get to it next time i consider playing

**Comment by nikothedude** [comment]
This is likely unrelated to pathfinding and more of a problem with the corpses. I changed how superior mobs handle stuns recently so maybe thats related.

**Comment by nikothedude** [comment]
Possible cause: dead mobs have density = TRUE

**Comment by nikothedude** [comment]
lines 784-791 are called on mob death, probably the cause
