### ISSUE TITLE
Ancient Robot Mobs stay aggroed forever

### ISSUE THREAD

**Issue by ApplePlastic** [sojourn-13/sojourn-station#3858]
Title is self explanatory. This affects Autonomous Sentinels and Forgotten Engineers, which have been quite literally reported to chase you forever, even trying to break down walls to get to you. Even if you are way out of their line of sight, the ranged mobs will still shoot at you with 100% accuracy with no aim warning, and act as if they are still in aggro range even if you change z-levels. This was reported some time ago, but I'm pretty sure it got shot down for some god-forsaken reason.

**Comment by Trilbyspaceclone** [comment]
Think this was fixed if it happens again let me know and reopen a new issue report
