### ISSUE TITLE
Syringe Stat requirements

### ISSUE THREAD

**Issue by Alterist** [sojourn-13/sojourn-station#3861]
From what i can find on the wiki and read of the code, Syringes can be used on yourself at either 10 BIO/20 COG or being an addict.
But when i tried using them with the stats I had as an outsider it gave me the "You have no idea how to properly use this syringe!" message.
![Untitled-1](https://user-images.githubusercontent.com/38592768/184891252-08344512-a626-4281-b604-b4a2fdf2a373.png)

**Comment by Trilbyspaceclone** [comment]
Ok so the reason for this is that is that you to use it on others need 15. This is an error on the wiki

**Comment by Trilbyspaceclone** [comment]
What wiki page is in question here?

**Comment by Trilbyspaceclone** [comment]
DM me with the link to the wiki page in question
