### ISSUE TITLE
another piping issue

### ISSUE THREAD

**Issue by Dissentbay** [sojourn-13/sojourn-station#3862]
so, wrenching a pipe with plasma in it, releases an infimal amount of plasma in the air, that apparently cannot be removed by any means (filtering or causing fires). That transforms that area into a spark hazard zone (anything that would cause a fire in a plasma environment sets only you and your square on fire)
how to reproduce the issue?
have a placed pipe with less than 400kpa of plasma in it
wrench it off
light a welder or anything that causes sparks
all in the same room
now you're on fire, good luck if you're not wearing protection

**Comment by Trilbyspaceclone** [comment]
This isnt a bug/code error

**Comment by Dissentbay** [comment]
I mean, that plasma cannot, by any player tools, be removed from the area
does not look like an intended consequence of the issue
