### ISSUE TITLE
Hull Dent Surgery Non-Functional

### ISSUE THREAD

**Issue by Luftkommando** [sojourn-13/sojourn-station#3873]
Encountered on-
> Server revision: master - YY/MM/DD 2022-08-19
> [eb6b6eb825cee9acc9a3bfc5bb802732bdc4a004](https://github.com/sojourn-13/sojourn-station/commit/eb6b6eb825cee9acc9a3bfc5bb802732bdc4a004)

Like it says on the tin, as of the noted revision it seems the hull dent surgery option does not function. If you are holding a non-welding tool, it will request that you use one but once you do have a welding tool the surgery option does nothing. There is no response on the text log and the damage to the limb does not decrease. On two separate rounds I attempted to use the hull dent surgery with an arc welder, a standard welder, and a Jolly Co-operation polytool. In addition I attempted the hull dent surgery option on a lightly damaged limb rather than a limb that strictly required the surgery. All three tested welder types and the damage test resulted in the same issue as noted prior. No response and no damage repaired on the affected limb.

For replicability I had three other persons attempt to repair the limb using the hull dent surgery and all three ran into the same issue noted before. No response in the text log and no damage repaired.

I did not have the chance to test if the hull dent surgery did not function on other players, only that it did not function when used on my character across those two rounds.

**Comment by Trilbyspaceclone** [comment]
Was the welder on? Im having issues replicating it

**Comment by Luftkommando** [comment]
> 

I tried it with and without them on and received the 'you need a tool with the welding quality' prompt when the welders were off and the mentioned issue when the welders were on.

I just tried it again and the surgery option was functional. So at this point in time I have no clue as to why the issue was present last night during those two rounds, nor why I could replicate it with other people having the same issue in those rounds. A mystery.
