### ISSUE TITLE
Fire stacks knock you unconscious and never go out

### ISSUE THREAD

**Issue by elgeonmb** [sojourn-13/sojourn-station#3876]
What it says on the tin, basically. A bunch of people have observed that their characters get lit on fire and then set into paincrit (humans) or forced to reboot from heat (robots) within seconds from even fairly small fires (like the kind you get from critfailing with a fuel-using tool). Because the fire never goes out without being extinguished, that means anyone who gets even slightly ignited without people nearby is doomed to sit and watch their character be slowly eaten alive by the world's smallest grease fire. Last time it happened to me it took fifteen minutes! It is not clear to me that this behavior is intended; if it is, it still sucks.

A while ago someone on the discord said it was a bug involving overwear, for some reason? So attempts to fix it might start there.

**Comment by Trilbyspaceclone** [comment]
Fire tends to be declared hecken unfair and all that but its working as Possum intended
