### ISSUE TITLE
Aberrant organs do essentially nothing.

### ISSUE THREAD

**Issue by LiteralMushroom** [sojourn-13/sojourn-station#3951]
All the hormones' effects are pretty much unnoticeable due to the fact that they're only secreted in tiny amounts and barely have any effect to begin with.

Non-hormone chems are pretty much all things that don't affect you or are straight-up **negative** (unless you're a cht'mant, maybe?), so they're ALSO not really worth ever using.

Aaaaand 3 points in a stat means basically nothing too.

**Comment by Trilbyspaceclone** [comment]
You were likely using lower tears for testing and learning, higher grade stuff is in the game and abtainable

**Comment by LiteralMushroom** [comment]
The ones you can print yourself should be average not useless.
