### ISSUE TITLE
prospector shuttle vents when moving from place to place

### ISSUE THREAD

**Issue by ChefDoggo** [sojourn-13/sojourn-station#3980]
got in the shuttle to move to greyson, got there perfectly fine no venting or anything and then on my way back to the landing pad the shuttle suddenly completely vented all air and pressure. not sure how to replicate it outside of just moving the shuttle around and seeing if it happens doesn't seem to fix itself either
Edit: having trash carts on it is what causes the vent, just figured that out now

![WHERES MY FUCKING AIR](https://user-images.githubusercontent.com/110652695/193350120-478c6660-91c4-4c73-b1a3-3e198da5404b.PNG)

**Comment by Trilbyspaceclone** [comment]
Unable to replicate

**Comment by ChefDoggo** [comment]
funny since T3 was messing around with shuttles not that long ago cause of the same issue

**Comment by ChefDoggo** [comment]
nevermind door timer trolled the fuck out of me AUUGGHHH muh air
