### ISSUE TITLE
Mycus Hair

### ISSUE THREAD

**Issue by MagniCarta** [sojourn-13/sojourn-station#4045]
Mycus hair options are incredibly brightened/whitened, even when selecting dark colours
![image](https://user-images.githubusercontent.com/112213960/197342884-7256322f-bfd2-45b6-83ba-dfaa766fc233.png)

**Comment by ThePainkiller** [comment]
This was fixed iirc

**Comment by cdb-is-not-good** [comment]
> This was fixed iirc
![image](https://github.com/sojourn-13/sojourn-station/assets/87905328/1688cc88-b93c-4d18-a369-1ea9a005f741)
It was not. The hairs are whitescale instead of blackscale as they should be, which is slightly annoying.

**Comment by Trilbyspaceclone** [comment]
Has been fixed more-so now
