### ISSUE TITLE
psionic knife doesn't despawn after getting embedded 

### ISSUE THREAD

**Issue by ChefDoggo** [sojourn-13/sojourn-station#4184]
doing maint goblin stuff as a psion, my psionic blade embedded (something it used to not do), ripped it out like i would any other weapon and tried to drop it at a later time expecting it to despawn. it uhhh didn't do that and was just a normal item

only way i can think it happened was by the actual embedding into a mob so to recreate just attack till your psionic blade embeds then yank it out and drop it, it should just stay there

**Comment by cdb-is-not-good** [comment]
For some reason whoever coded the shit failed to give it embed_mult so it has the same chance of embedding as a kitchen knife. Jawesome! Will fix.
