### ISSUE TITLE
Small new UI issue.

### ISSUE THREAD

**Issue by 1yakynm** [sojourn-13/sojourn-station#4304]
Not entirely certain if this is an issue with the fresh UI system or a local issue that happened due to a one-in-a-thousand times minor issue, but I'm not able to see the drone interface at all. Abilities are there, but there is no hotbar for me to select tools. This may also be the case for other Silicons and possibly AI - other playable creatures that were likely overlooked during the UI integration.

**Comment by 1yakynm** [comment]
![image](https://user-images.githubusercontent.com/112587045/212896977-7661bd63-a9b0-4734-b6e3-2be06b5e940d.png)

**Comment by 1yakynm** [comment]
Should also note that I reconnected several times, and restarted dream seeker, which did not work at all, further suggesting that this is a UI issue.

**Comment by Trilbyspaceclone** [comment]
Cant replicate anymore but this was a issue that was fixed
