### ISSUE TITLE
SI tesla Turrets.

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4354]
SI tesla turrets attack SI robotics drones. Not roombas but mantis and sword drones. Of lesser importance they attack cleanbots and likely other bots.

**Comment by cdb-is-not-good** [comment]
Currently working on this, frankly Im NOT SURE what the difference is between a cleanbot/mantisbot and the custom roomba that the turrets are freaking out about. This is a weird one.

**Comment by cdb-is-not-good** [comment]
some of the code to identify friend from foe was committed out, putting it back in seems to have fixed the issue and the turrets seem to be working - Though I reached out to the coder responsible for both reworking them and also commenting out the code in the first place. Fixed in #4685
