### ISSUE TITLE
Bar/Kitchen Issues as of #4470

### ISSUE THREAD

**Issue by Dumbdumn5** [sojourn-13/sojourn-station#4524]
#4470 Unintentionally didn't include the Booze-O-Mat or the Dinnerware Vendor, whoops!
Kitchen and Bar have no sinks at present which are important for meals and dumping improper drinks.
Bar shutters only close over the entire bar, with the 'south bar access' button meant for shielding the till not doing anything.
Kitchen lacks a blender.
Bar lacks a cigarette vendor.
Kitchen's 'buffet' windows exist as shutters, but have no button or way to open them in the kitchen itself.

**Comment by Dumbdumn5** [comment]
Also of note! Kitchen lacks a sink.

**Comment by Trilbyspaceclone** [comment]
Got them all I think
