### ISSUE TITLE
Sanity System Breaks Desires

### ISSUE THREAD

**Issue by Dumbdumn5** [sojourn-13/sojourn-station#4527]
Upon reaching max insight, produces this message.
![image](https://user-images.githubusercontent.com/12074028/223952222-94b37b0b-c743-4a59-9161-8ed3bfd16f27.png)
Naturally, means you can't 'level up', and breaks the desire system.

**Comment by Trilbyspaceclone** [comment]
Read chat, when clicking the eye it tells you, and lists what you want...
