### ISSUE TITLE
Soteria Outpost (Basement) not hooked into Colony's Power Grid

### ISSUE THREAD

**Issue by AysheDaArtist** [sojourn-13/sojourn-station#4611]
For several shifts, it's been observed that Soteria Outpost (Basement) is not receiving Power.  Playing as Guild, hooking it myself, and checking two hours later as ghost shown that every other SMES was 100% but Soteria Outpost (Basement) receives no power.

I believe this is a map issue and a wire is needed to be connected to Soteria Outpost (Basement)

**Comment by du-top** [comment]
As I understood it, it should be fixed by the changes in #4664

**Comment by SkinkHunt** [comment]
> For several shifts, it's been observed that Soteria Outpost (Basement) is not receiving Power. Playing as Guild, hooking it myself, and checking two hours later as ghost shown that every other SMES was 100% but Soteria Outpost (Basement) receives no power.
> 
> I believe this is a map issue and a wire is needed to be connected to Soteria Outpost (Basement)

It is already fixed. I just know know how to mark things as fixed yet

**Comment by du-top** [comment]
I think you don't have the permissions. You should have mentioned something like "fixes #4611" in your PR.
