### ISSUE TITLE
control alt click terminal for modular computers is broken.

### ISSUE THREAD

**Issue by DorfGuy1** [sojourn-13/sojourn-station#4638]
When you control-alt  click on a computer, or pda, you get a terminal prompt. However, it does not work and is completely unresponsive. Someone said this was due to TGUI.

**Comment by cdb-is-not-good** [comment]
A little late but unable to recreate at this time.

**Comment by cdb-is-not-good** [comment]
Closing for now as issue appears either gone or unreproducible under described conditions.
