### ISSUE TITLE
marshal shuttle dun work 

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4660]
To recreate: attempt to fly marshal shuttle. Select landing zone. Hit the launch button 500 times and cry as nothing happens.

**Comment by cdb-is-not-good** [comment]
Seems like it's very possibly all commented out. Will take a look maybe.

**Comment by cdb-is-not-good** [comment]
Nope, I stand corrected. Just had its starting-location set incorrect, fixe is up.
