### ISSUE TITLE
Duty carbine sprite issue.

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4671]
The duty carbine is missing a empty (as in 0 bullets in the drum) and loaded with drum sprite. Possibly other states as well worth checking.

**Comment by du-top** [comment]
Confirmed, if the Duty (/obj/item/gun/projectile/automatic/duty) is loaded with a drum (/obj/item/ammo_magazine/light_rifle_257_drum) and you shoot with it until it's empty, icon_state is "duty_mag50_slide", which has no icon.
But before it's empty (well, one round counts as empty), there is an icon. So could you elaborate on the "loaded with drum" part? What did you do differently? Other drum? There seems to be none for a 75 rounds mag.
