### ISSUE TITLE
Nanobot computers 

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4672]
Seen it awhile ago as far as I'm aware it was not fixed. Nanobot computers don't get any computer parts. Suppose to have all of the best  computer parts in the game. Not sure if it was a some intended balance thing or what (hope not who cares about a OP computer?)

**Comment by cdb-is-not-good** [comment]
![image](https://github.com/sojourn-13/sojourn-station/assets/87905328/6cdcad26-3890-4be3-9408-1731280d35b1)
it appears this is no longer an issue.

**Comment by cdb-is-not-good** [comment]
Closing this for now. If it turns out to be an issue still just poke me on discord and I'll fix it then and there.

**Comment by benj8560** [comment]
you created one via a nanobot and did not just spawn it in I assume? If so then guess it's somehow fixed....not sure how I seen it on multiple rounds with others suffering the same issue.

**Comment by benj8560** [comment]
well had to see it for myself sureanuff does seem to be fixed or perhaps it's not consistent? Weird regardless should I or someone else see it again worry about it then I guess.
