### ISSUE TITLE
FBP/Robotic limb problem.

### ISSUE THREAD

**Issue by 1yakynm** [sojourn-13/sojourn-station#4674]
Every single limb, or body part, is reduced to 10% of the max health in it's robotic state, regardless of the model, including the internal parts like the frame. I would be willing to bet that Rebel's retarded overhaul even dunked down on the supposed combat robotic body parts, like Blackshield and Excelsior. 

Morever. Any injury taken on a robotic limb is calculated in such a way, that it acts as if they are on low health to begin with when getting injured, resulting in a titanic amount of pain damage. Meaning, that FBPs no longer have any meaningful gameplay aside from just going paincrit after being shot at with a laser a couple times.

It's not rocket science to figure out that this isn't how a videogame is supposed to operate.

**Comment by cdb-is-not-good** [comment]
Need a little bit of clarification. the total health of the limb is 10% of the coded value? It's 10% of its normal max?

**Comment by 1yakynm** [comment]
Here are health values for all internal parts of a ***blackshield*** limb, that is supposed to be """""tougher"""" than baseline prosthetics available to the general public. Yet it's internal health values are totally fucking similar to any other prosthetic. Morever, base health value for an organic arm bone, is fifty (iirc). Robotic arm frame is fourteen.
![image](https://github.com/sojourn-13/sojourn-station/assets/112587045/cd1ab760-b7ae-4a29-9764-960af40b37b4)

**Comment by 1yakynm** [comment]
I am sure that you can do some playtesting on your own with an FBP character and get shot by an NPC with a laser only to fall into a pain crit after a few shots.

**Comment by 1yakynm** [comment]
i should also note that it WASN'T so fucking low before, and was, on par with organic. Fifthy health points

**Comment by 1yakynm** [comment]
fifty

**Comment by cdb-is-not-good** [comment]
Some slight testing, yes it appears robotic limbs have _half_, not 10%, of the total health of an organic limb. This i suspect was a balance change to make up for robots not feeling pain, not bleeding, being easy to fix, etc- They DO seem to take halloss though, which is an issue for that balance.

**Comment by cdb-is-not-good** [comment]
I will probably want to do two things in response to this issue. A. FIX robots taking pain, if we want them to be a little more brittle in exchange for being easier to fix, not having pain, etc- that's fine but we need to stick with that until a change is made. B. maybe adjust robot baseline armor values? At least, for the synths that deserve it, anyway.

**Comment by cdb-is-not-good** [comment]
A little bit of testing and Im not honestly sure that limb health needs any tweaking, in light of synthetics benefits.

**Comment by cdb-is-not-good** [comment]
Personal testing, speaking to a few synth players and generally mulling this over and I do not believe this matter requires addressing at this time. Obviously folks are free to make a PR to change things if they wish, but I'll be closing this issue report as it's not relating to an actual bug, but a balance matter.
