### ISSUE TITLE
Robotic organ issue.

### ISSUE THREAD

**Issue by 1yakynm** [sojourn-13/sojourn-station#4675]
Even though you are able to pick yourself a robotic 'torso' body part with some shenanigans, you still aren't able to modify the organs, when going for a biosynth build. This isn't limited to the brain or the eyes. 

Even though choosing a robotic torso forces all of the internal organs into their robotic state, including the brain, they aren't able to be altered into the biological state, with the menu stating that it's impossible for a biological organ to be attached to a robot torso.

It contradicts itself, however. As soon as you spawn and open up your robotic chest, or head, you find a full set of human organs, eyes, and the brain, all biological. You have no control over it. 

Nor can you really 'attach' a robotic torso, as there is no set button to it, aside from when you open the augmentation menu for the first time. And you cannot go back to this torso selection until the server restarts.

**Comment by cdb-is-not-good** [comment]
Ah, this is a slightly old issue. the robot torso/heads aren't supposed to be selectable since that's not how we actually *do* robotpeople. Will take a look at locking those back off.

**Comment by 1yakynm** [comment]
how about biosynths being a legit in-game race? They are supposedly akin to an FBP, in that they are fully robotic, but still have human organs. That just magically disappeared?

**Comment by cdb-is-not-good** [comment]
Biosynths are not /quite/ that, it's a bit of an umbrella term to describe synthetics that use organic parts. There have both been biosynths that are fully organic synthetic organisms perhaps with a robotic brain and mostly robotic organisms with organic components. They're also rather not implemented, but perhaps that is a code project for another time
