### ISSUE TITLE
Magical weapon restoration.

### ISSUE THREAD

**Issue by 1yakynm** [sojourn-13/sojourn-station#4677]
Some sawed-down weapons (Although I am 99% sure that it's an issue for all of them) can be disassembled with wirecutters and put back together to get a whole version of the gun without the need to go through the crafting menu and spending resources. 

Similar trick can also be performed on the psyonic analog of the grease gun, in which case, by pulling it apart, you can make the real gun, which is a straight upgrade from the psi-version.

**Comment by cdb-is-not-good** [comment]
Needs more details. Disassembled with wirecutters, then put back together how? with wirecutters? With materials? Other tools?

**Comment by 1yakynm** [comment]
Yeah. And maybe do something about laser weapon disassembly being a thing. You can actually pull them apart but they are going to give you one piece of steel for each part that is supposed to be there, and one (i assume) baseplate part that is supposed to be a frame but doesn't do anything.

**Comment by cdb-is-not-good** [comment]
Doable, can likely give energy weapons a little thing that prevents you from disassembling them and just tells you 'this weapon is far too complicated to field strip' or similar.
