### ISSUE TITLE
Mop bucket sprite not updated when empty

### ISSUE THREAD

**Issue by du-top** [sojourn-13/sojourn-station#4690]
When the mop bucket is empty, the sprite will only be updated if you, for example, put the mop back in. It just having 0 contents won't update the sprite.

**Comment by cdb-is-not-good** [comment]
probably needs a whjateverthefuck to update the sprite whenever you add/remove contents from

**Comment by du-top** [comment]
Don't want to be an ass, but it's not solved yet.

**Comment by du-top** [comment]
Ah, now I got it! Sorry, I didn't mention that I meant the mop bucket _when it is attached to the cart_! I'm a victim of my routine. There would be a an easy fix, just calling update_icon after removing water via mop/rag/soap. Testing it right now, will create a PR if it works.
