### ISSUE TITLE
Message when using meat spike incorrect

### ISSUE THREAD

**Issue by du-top** [sojourn-13/sojourn-station#4691]
When using the meat spike, you have to grab the animal (god I hope you're using an animal, you savage). Click with it on the meat spike. You'll get a message telling you need to grab the animal by the neck. Do that (red, GRAB_NECK). Try again. Same message. _Tighten the grab on the neck_ (red flashing, GRAB_KILL) and click. No message, it works. The message is talking about grabbing by the neck, but means the tighter grab by the neck / kill grab.

code/game/objects/structures/kitchen_spike.dm:21

**Comment by cdb-is-not-good** [comment]
Ah, you need to be literally strangling the animal? should be easy fix.

**Comment by du-top** [comment]
Just a misleading text causing you a "But I AM DOING THAT!" moment the first time.
