### ISSUE TITLE
Tesla Turret No Workie Right

### ISSUE THREAD

**Issue by Nep993** [sojourn-13/sojourn-station#4702]
Tesla turrets somehow put more power into a room than they draw. 
![image](https://github.com/sojourn-13/sojourn-station/assets/66002259/60954427-9b43-4c9b-b4dc-cb1e9ce319fa)
(yes ik it's from another server, but it's the same code and it's been verified by XVIII The Moon as being an issue on server)

**Comment by cdb-is-not-good** [comment]
Pained emoji. Thankfuly after testing the things give the room infinite power but don't actually put more power into the grid, still a bit of a PROBLEM.

**Comment by Trilbyspaceclone** [comment]
Should have been fixed in multal prs.
