### ISSUE TITLE
Poly is a scuffed bird

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4705]
So poly. I'm sure anyone whos ever been on a TG sever recalls him collecting items and piling them on something. Are poly does this to....sorta. Issue is he only picks things up and never drops them unless you kill him. Every day he takes the GMs stamp. One time I had him steal a tool mod out of my hands and the only way to get it back was a bullet. His AI seems pretty dated and broken.

A lazy fix could be just mapping him somewhere he has something to steal away from the stamp once he gets his one thing he's happy.

**Comment by cdb-is-not-good** [comment]
I hate this stupid bird.

**Comment by benj8560** [comment]
me to. That tool mod was the ONLY good bluespace paint to ever come out of my closet. I shot him dead and did not feel bad

**Comment by benj8560** [comment]
Pushed a update to PR #4883 moving Poly away from the stamp. Band-Aid fix and his AI is still very scuffed so this issue will remain open

**Comment by benj8560** [comment]
oh right. This is fixed apparently poly just needed a filing cabinet to be happy someone added one and fixed it by total mistake doing so.
