### ISSUE TITLE
shit bullet oh shit bullet, where art thou

### ISSUE THREAD

**Issue by ChefDoggo** [sojourn-13/sojourn-station#4713]
caustic rounds do literally nothing to humans, they hit and cause a stumble but don't actually do damage to any degree (tested by CDB), still works on mobs because they still track toxin damage but does absolute dickall to a player/nonsimple mob, the mobs only take toxin damage from the bullets

recreate by literally using the bullet in a gun of your choice

**Comment by cdb-is-not-good** [comment]
Give your issue reports proper titles. Fixed.
