### ISSUE TITLE
Synths don't have DNA

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4715]
Could be intended? Could be it got broken or just no one remembered to do it. generally on SS13 synths retain DNA just for the sake of forensics and other things in my case DNA lock triggers. Now yes there is no reason synths should have DNA but it can be easily choked up to them somehow simulating it due to some kind of regulations. They still have fingerprints for example.

**Comment by cdb-is-not-good** [comment]
this is in fact intended AFAIK

**Comment by benj8560** [comment]
I assumed. I just felt it abit silly given they have obviously artificial fingerprints.....at the same time perhaps there was a good reason for this I know random mutations from radiation behave a bit weirdly in some circumstances. Can close it if you want figured it was worth bringing up. 

I've been under the impression DNA lock going on with no message or anything ment it was working. Up until being surprised very rudely.

**Comment by benj8560** [comment]
Or at least records say they have prints. At this point we're not even be surprised if they didn't.....and now that I think about it I'm pretty sure I recall using DNA locks on mechs as synth?

**Comment by cdb-is-not-good** [comment]
> I assumed. I just felt it abit silly given they have obviously artificial fingerprints.....at the same time perhaps there was a good reason for this I know random mutations from radiation behave a bit weirdly in some circumstances. Can close it if you want figured it was worth bringing up.
> 
> I've been under the impression DNA lock going on with no message or anything ment it was working. Up until being surprised very rudely.

....DO THEY?

**Comment by cdb-is-not-good** [comment]
they have fingerprints???

**Comment by benj8560** [comment]
They show up on record with them if memory serves me right. Don't believe I've ever actually checked one with forensics or anything. And....they really need to if they don't and this is just some quirk. All they would have to do is get naked and boom they are immune to forensics.

**Comment by benj8560** [comment]
![dreamseeker_ldknqCmSoC](https://github.com/sojourn-13/sojourn-station/assets/26511091/9cd2c35d-6bbf-4847-b8b2-78c6099633c6)


DNA locked as a synth. Could not get anyone around to truly test if they could not enter it

**Comment by benj8560** [comment]
old issue but I looked into this more...turns out DNA locks DO Work on synths. DNA locks are just...super super quirky and scuffed. You have to place a DNA locked weapon on the GROUND then pick it up to ''sync'' it they work just fine for robot gang.
