### ISSUE TITLE
odd hypospray behavior 

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4716]
I've noticed some....strange things with the hypospray. Sometimes it can take upwards of nearly a full minute to inject someone or be instant. It varies widely aside from seeming consistent on a round to round basis. Yes I am fully aware that if someone is on harm intent it will slow it down a small amount but this is far far longer then that. That gives a custom message to the person using it. This is not that no such message appears. It's meant to be the fastest means of injection on the sever but....with this little inconsistency between rounds it makes syringes more reliable. 

I seen this highly severe inject time once after injecting someone in a RIG took a lot longer then a syringe and then seemed lock onto that long ass inject time for the round. Mostly a guess but perhaps that's something

**Comment by cdb-is-not-good** [comment]
Unable to reproduce, needs more info

**Comment by benj8560** [comment]
Suppose I'll make a video or something if it shows up again.  Usually starts happening deep into the round

**Comment by benj8560** [comment]
I seen this again the other day it does seem related to trying to inject into someone with space suit on. It takes awhile longer then a syringe to do so then after injecting them every following injection regardless of armor or not will be the same slow ass time.

**Comment by cdb-is-not-good** [comment]
That's normal, actually. Suits take longer to inject into.

**Comment by benj8560** [comment]
still not understanding me. I inject someone in a suit and as expected it has a delayed injection then AFTER if I inject someone without armor the injection has the same delay on it. I believe that's whats happening. Somehow the injection delay is permanently sticking to the spray.
