### ISSUE TITLE
Synths wanna dive!

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4718]
So at the moment synths are a tad weird. They clearly have a hunger stat that effects nothing but diving. At the moment they can maybe dive 5-10 times per round then they become to ''hungry'' to dive. Something as simple as making them very very slowly regain hunger all on their own would likely be a easy simple fix. Otherwise create some kind of mechanic around it I'd just like to be able to regain it somehow rather then feeling like my dives are a limited supply. 

Edit: also please please do not give them endless diving. I don't wanna see some gooofy shit like synths diving around all over the place non-stop in combat or just being little goobers with spamming it. Somethings tgotta cut them off so they can't short term spam it

**Comment by cdb-is-not-good** [comment]
uirrgfhgh known issue for a while now, yea. I guess the "easy" way would be- idk, an IS_ROBOT check and if so maybe just make it be on a cooldown?

**Comment by benj8560** [comment]
I'd personally like it to be a bit spam able but only a few times short term. Usually with diving you'll dive over a table then need to dive back over again very soon after. Still beggars can't be choosers. I was imagining more just making it so synths very very very slowly gain hunger rather then lose it. Call it capacitors charging or whatever you want.

**Comment by benj8560** [comment]
realising that kinda conflicts what I said I'm a lil stupid sometimes. 
But yeah lil short spam = good.
Lotta short spam = funni but bad

Also dives are kinda just.....quirky here and can be hard to pull off thanks to the sever lag. Little bit of a buffer of idunno 3 dives before its a issue mostly to make up for the fact my dives don't even work out half the time.
