### ISSUE TITLE
armor alt skins fucked

### ISSUE THREAD

**Issue by ChefDoggo** [sojourn-13/sojourn-station#4724]
armor like the CO's full vest and if i remember correctly armor like the mark V protection (something with no alt skin) has issues with the Adjust style where it defaults it to a skin that is 100% NOT the intended skin for the sprite

i am livid

**Comment by benj8560** [comment]
SI's mark 2 armor has this same issue.

**Comment by cdb-is-not-good** [comment]
Im not sure what fool fucked this up.

**Comment by cdb-is-not-good** [comment]
THIS kinda shit is why I did not want to use change_appearance for literally everything.
