### ISSUE TITLE
Food desires kinda suck and be broken. I assume

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4727]
Ever since sanity got put in I've noticed very little returns doing food desires. Used to be super food from the Hex cooking machines was as sure fire way to gain desires and now I find it near impossible to gain desire from food to the point I just see a food only desire as a loss on stat gain at this point.

**Comment by benj8560** [comment]
Just tested this outright. Had a 4No Raisins desire one that is usually the best due to 4No Raisins being chewy and having a lot of bites. Gained 0 Rest progress from it

**Comment by Trilbyspaceclone** [comment]
Fixed in the linked issue
