### ISSUE TITLE
Mapping: robotics go boom (again)

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4731]
This was a issue on are old map. We FIXED it then went and did it again on the new map. There is a welding fuel tank lined up to get shot by a vender and EN being ideal target for it. An easy fix is relocating the welding fuel tank to the back storage room where the ADMS lives.

![dreamseeker_kHcGGZoG9Q](https://github.com/sojourn-13/sojourn-station/assets/26511091/44f5ceee-5d8e-42f5-bd29-119676cac6f1)

My suggested location: 
![dreamseeker_JbKlAStnMz](https://github.com/sojourn-13/sojourn-station/assets/26511091/7c30b09d-f8f2-4fba-a209-94d472e3eaff)

**Comment by cdb-is-not-good** [comment]
that's so funny
