### ISSUE TITLE
opifex black medical webbing selectable in loadout/Time to make someone sad.

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4734]
not sure much else needs saying and got tired of seeing players over many many months abuse it. Can be picked in the loadout. I assume its a bug? 

![QV2mPNZ16n](https://github.com/sojourn-13/sojourn-station/assets/26511091/5041ad2e-fa5f-4a50-b7b5-5a8c8c4a888e)

**Comment by cdb-is-not-good** [comment]
Less a bug more an oversight but it's definitely not ideal. This is why we do pathing not wrong.
