### ISSUE TITLE
airlock crafting

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4743]
Airlock crafting is missing. Simple as

![image](https://github.com/sojourn-13/sojourn-station/assets/26511091/e1299ef0-6751-4d51-a076-4f268eb83feb)

**Comment by cdb-is-not-good** [comment]
turns out it's not a bug. Airlock crafting is locked to the handyman perk and if you lack it, you dont even see the tab. I guess empty tabs are invisible?

**Comment by benj8560** [comment]
thats.....very stupid but okay?
