### ISSUE TITLE
Core implant objectives.

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4771]
so appears you can get the convert objective with a psionic organ and I assume any core implant. 
![dreamseeker_BuAmbAaugM](https://github.com/sojourn-13/sojourn-station/assets/26511091/c584b930-980d-42dd-8d8a-f49b6837a3bd)

Not bug related but this objective should honestly just be removed or have it's limited antag status removed? Force conversions really don't fit are church lore.

**Comment by cdb-is-not-good** [comment]
Ah yea this one can probably go away
