### ISSUE TITLE
Lodge is wired incorrectly

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4773]
caused by #4772 

![dreamseeker_kiNat57vAS](https://github.com/sojourn-13/sojourn-station/assets/26511091/c6bb153f-485f-4291-8e6e-327bef2134f4)

Wired backwards. The terminal is the output while under the SMES is the input

**Comment by benj8560** [comment]
hm no Im mistaken. Under the SMES is output I'm not really sure whats doing this? Perhaps that odd bug where a single cable will decide to not send power I'll see if I can locate said cable

**Comment by benj8560** [comment]
I believe it's one of the 3 wires directly under and to the south of the SMES not sure what ones. Also not really sure the fixed used on this in the past. Used to be lower SI had the same issue and I wanna say Skink fixed it? But I'm not fully sure

**Comment by Trilbyspaceclone** [comment]
fixed with #5199
