### ISSUE TITLE
Somatorays do not induce greater mutations.

### ISSUE THREAD

**Issue by Andron1219** [sojourn-13/sojourn-station#4784]
For some reason the Somatoray does not use the greater mutations, instead pulling from the lesser mutations table.

Can be recreated by simply doing a plant with greater mutations and attempting to mutate it, it will result in a lesser mutation.

Paths that (to my knowledge) reference this are;
https://github.com/sojourn-13/sojourn-station/blob/master/code/modules/hydroponics/trays/tray.dm
https://github.com/sojourn-13/sojourn-station/blob/master/code/modules/projectiles/guns/energy/misc/floragun.dm
https://github.com/sojourn-13/sojourn-station/blob/master/code/modules/hydroponics/seed.dm
https://github.com/sojourn-13/sojourn-station/blob/master/code/modules/hydroponics/seed_datums.dm
https://github.com/sojourn-13/sojourn-station/blob/master/code/modules/projectiles/projectile/special.dm

**Comment by benj8560** [comment]
oh there WAS a issue for this! If you could pretty pweas close this it was fixed in #5086
