### ISSUE TITLE
Blood capacity magicly reducing

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4822]
So I've been noticing a ongoing trend of blood capacity slowly getting reduced and never coming back after I THINK being exposed to very mild toxins for  extended periods of time. The blood capacity never returns even after fully healing all the damage caused by it. The only bandaid fix I've found for this IC is the blood banks genetics gene. Not a very ideal fix....but I've consistently seen it happen on a character that smokes TOHA every day. (honey is very midly toxic but usually wont kill you). consistently as in EVERY round I'll see my blood capacity reduce a little bit. This in its extremes kinda cripples the player not all to fun. NSA capacity also seems to get reduced at the same time.

**Comment by benj8560** [comment]
Also! Far from a new issue...I believe this started when...I forget what caused it but I noticed it way back when everyone was complaining about smoking killing you. I had just not noticed what exactly was causing it at the time and it's become much much worse with the recent changes to toxins or well at least much more noticable

**Comment by Trilbyspaceclone** [comment]
If this happens again let me know on the discord and ill reopen the issue but until we can confirm this bug is still present its likely fixed somehow
