### ISSUE TITLE
Weird stats' naming?

### ISSUE THREAD

**Issue by ghost** [sojourn-13/sojourn-station#4861]
So, this isn't really an issue but some weird choices?

code/__DEFINES/mob_stats.dm
```
#define STAT_LEVEL_NONE     0
#define STAT_LEVEL_BASIC    15
#define STAT_LEVEL_ADEPT    25
#define STAT_LEVEL_EXPERT   40
#define STAT_LEVEL_PROF     60
#define STAT_LEVEL_GODLIKE	80
```

code/datums/mob_stats.dm
```
/proc/statPointsToLevel(var/points)
	switch(points)
		if (-1000 to -50)
			return "Hopeless"
		if (-50 to -25)
			return "Inept"
		if (-25 to -1)
			return "Misinformed"
		if (STAT_LEVEL_NONE to STAT_LEVEL_BASIC)
			return "Untrained"
		if (STAT_LEVEL_BASIC to STAT_LEVEL_ADEPT)
			return "Basic"
		if (STAT_LEVEL_ADEPT to STAT_LEVEL_EXPERT)
			return "Adept"
		if (STAT_LEVEL_EXPERT to STAT_LEVEL_PROF)
			return "Expert"
		if (STAT_LEVEL_PROF to INFINITY)
			return "Master"
```
It feels weird to me 
1)STAT_LEVEL_PROF goes straight to INFINITY while there is a next limit, GODLIKE.(The in-game naming for player will probably remain the same/be changed in section 1)
1.1)We can add more defines for negative(-1000 up to -1) stats.
2)why there is Master, while we cleary can put Godlike for simplicity and for easier future references.
STAT_LEVEL_GODLIKE is also used in code for stuff, so why we don't use it here?

**Comment by ActuallyALovelyGrave** [comment]
@Trilbyspaceclone Also, hi! I hope you are doin' well.

**Comment by Trilbyspaceclone** [comment]
Sorry for never noticing this, github never notified me of this???

Anywho to give some explainations
-50 is *really really hard* to get
-1000 is just a ketch all in case someone gets below -50

Nothing being past 60 for prof is just do me not coding it, I likely didnt have a name or forgot godlike was a thing

**Comment by ActuallyALovelyGrave** [comment]
Sure, it never did.
