### ISSUE TITLE
rad resistance gene not always working

### ISSUE THREAD

**Issue by benj8560** [sojourn-13/sojourn-station#4866]
found so far two cases of the rad resist xenogenetics gene not working. Currently Kaisers being the primary issue their bile and possibly the other way they make rads. Not tested super throughly but SOMETHING they do is doing it.

Little more niche of a issue rads from Xenoarch anomalies seem to cause issue as well.

**Comment by Andron1219** [comment]
This also extends to Cindarites not being radiation immune anymore (which they should be immune), probably still using the old radiation damage system.

**Comment by benj8560** [comment]
fixed
