### ISSUE TITLE
Hunter's Lodge Hydro Containers Restricted

### ISSUE THREAD

**Issue by verywhiterabit** [sojourn-13/sojourn-station#4901]
The Card Reader Trash Bin and Access Restricted Hydroponics Crate in the hunter's lodge hydroponics area are not accessible by hunters. 

Apparently an unintentional oversight. 

![image](https://github.com/sojourn-13/sojourn-station/assets/24979527/ce4d61c7-5447-43ce-9918-d5c164f874ba)

**Comment by benj8560** [comment]
right so somehow the hunters z-level is getting oldification on most of the crates/closets I noticed this awhile back. I'm pretty sure thats why this is happening. Random ID locking is something oldification will do to any type of crate.
