### ISSUE TITLE
bags are eating tools HP

### ISSUE THREAD

**Issue by ChefDoggo** [sojourn-13/sojourn-station#4984]
putting a tool (in this case the overseers swords, ritual knife and im assuming other tools as well) into a bag (or at least satchel) and removing them deals damage to the tool. unkosher please fix coder people

easy recreation, take tool, put into bag, pull out of bag, inspect

tried it on a ritual knife, took ~2.8 damage just from taking it out of a bag, not fun considering repairing tools takes away from their max HP

**Comment by Trilbyspaceclone** [comment]
Not a bug. holstering/storing items uses durability
