### ISSUE TITLE
Nanobot repairs are wonky

### ISSUE THREAD

**Issue by 1yakynm** [sojourn-13/sojourn-station#5234]
I don't have any necessary knowledge to properly explain the issue, but i'll do so to the best of my ability.

If you never pick the autorepair for the nanobot, and have to repair it manually, your repairs reset as soon as you walk away from the nanobot. Or at least it appears as such when you examine them.

Example:

Nanobot has 23% HP

I repair it once, twice, thrice until the game tells me that it is at full HP
I walk away a tile
I examine the nanobot after repairing it, it's back to 23% HP

Same happens when i turn off my welding tool and stand on the tile adjacent to the nanobot.

I should note that i don't know if it usually takes time to repair a nanobot like any action would, since i play a roboticist and all my repairs are expert level

If i had to guess it has something to do with action times, maybe it's set to the negative value if you have Robotics expert, and thus goes on indefinitely until you walk away which cancels the action.

**Comment by Trilbyspaceclone** [comment]
This is do to toxin/halloss damage not being repairable
