### ISSUE TITLE
Medborg's inject rapier issues

### ISSUE THREAD

**Issue by 1yakynm** [sojourn-13/sojourn-station#5288]
Thus far i've noticed that it will melt when injected with polytrinic acid (or, any acid, more than likely), and actually has durability, which is problematic when it has no adhesive item of any quality to speak of to repair it itself.
![image](https://github.com/sojourn-13/sojourn-station/assets/112587045/4ad044e0-fa88-49e0-b275-aa9620a9ebff)

**Comment by Trilbyspaceclone** [comment]
Well the acid thing is a bug
The durablity is set much lower then normal weapons, so it is able to break like any other head of staff uniquic sword or weapon

**Comment by Trilbyspaceclone** [comment]
Apond further reading it seems borg tool durablity setting is bugged?
