### ISSUE TITLE
All borg guns no longer work.

### ISSUE THREAD

**Issue by 1yakynm** [sojourn-13/sojourn-station#5361]
I am not particularly sure if it is related to the recent bulk combat merge or not, but you can't toggle the safety on any of the Defense Cyborg's weaponry. Same might be true for the other models equipped with any kind of a weapon.

toggle_gun_safety does nothing, even when the weapon is in the active slot / in the passive slot. Right clicking on the weapon icon when it 's in your active slot does nothing. 

This is true for the integrated STS and the flare gun.

Again, not sure if this is true for the other cyborg's weaponry. 
![image](https://github.com/sojourn-13/sojourn-station/assets/112587045/2e94062a-0088-4414-ae99-229ab7bb5591)

**Comment by 1yakynm** [comment]
After changing the module to Custodial, which has the embedded SMG, the issue stays the same. No method of turning off safety works anymore. It is definitely the same for every other cyborg firearm.
![image](https://github.com/sojourn-13/sojourn-station/assets/112587045/8d915a69-9770-4ee0-aaef-4c5650be06a0)

**Comment by Trilbyspaceclone** [comment]
Alt Click the fire arm to toggle its safty off

**Comment by 1yakynm** [comment]
yeah i noticed. I am dumb, thank you.
