### ISSUE TITLE
Science borg 'Destructive Analyzer' Rapier does not work.

### ISSUE THREAD

**Issue by 1yakynm** [sojourn-13/sojourn-station#5363]
Maybe it's intentional, maybe it does not work, i have no idea. But the description says that it *should* transmit research points to the database, and when i do what it says on the tin - nothing happens.

**Comment by Trilbyspaceclone** [comment]
You hit it with your science tool, the science tool then holds the points for you to hit the science tool to the console to transfer it.
Its a 3 step process
