### ISSUE TITLE
Fluctuating Artistic gun prices despite them being already created.

### ISSUE THREAD

**Issue by PvtStupidhead** [sojourn-13/sojourn-station#5528]
![image](https://github.com/sojourn-13/sojourn-station/assets/4553139/60dce972-a456-4272-8ec5-1be358abf6b9)
As you can see, despite the weapon already being created, it'll constantly shift it's selling price: from two thousand to a few hundred bucks. Super strange.

![image](https://github.com/sojourn-13/sojourn-station/assets/4553139/bcd725b7-b932-4bf4-8ca0-ceb39fc02f31)

**Comment by Trilbyspaceclone** [comment]
This is an intented feature the price every call is randomized
