### ISSUE TITLE
Activating and then wielding the DOOMBRINGER chainsaw causes all damage from activation to be lost.

### ISSUE THREAD

**Issue by PvtStupidhead** [sojourn-13/sojourn-station#5568]
As title says, if you take the DOOMBRINGER chainsaw and activate it, then wield the weapon, you'll lose all damage you would've gained from activating it. Turning it off and on won't reset the damage either, in fact it'll nerf the damage on non-powered attacks too (and penetration if I remember right).  The only way to regain the damage is to put it in a container (maybe drop it too?) like a belt.

If you however, wield the DOOMBRINGER first, then activate it (or just activate it in one hand and not wield it) you'll still maintain the damage it would've normally granted and the armor penetration as well.

**Comment by Trilbyspaceclone** [comment]
Fixed in commit to #5539
