### ISSUE TITLE
Artists randomly lose ability to gain insight (lose sanity) from environment

### ISSUE THREAD

**Issue by PvtStupidhead** [sojourn-13/sojourn-station#5571]
As per most of the times when you are trying to get sanity by fighting or gibs, it will usually go just fine. However, I've now experienced 3 times where I cannot lose sanity (and thus gain insight) from filth, runes or graffiti and makes it so you are in effect worthless (more than you already are). 

So far, when it has occured I have used up 100 insight to make something, and then  when the insight reaches like about halfway sanity will suddenly no longer be lost. This has honestly occured 3 times, and 2 of them were shortly after I used 100 insight to make something. However, some shifts I have used 100 insight multiple times with no effect apparent, so it seems to just be at random times for the lols. 

I usually do a routine of running to the giant jelly-bloat pit with the materials, killing anything on the way, then go to the abandoned library to get anomalies, in case anything can be figured out on that route.

PS: I had basic vigilance when this occured.

**Comment by benj8560** [comment]
personally witnessed it happen a few times on Johan. Really not sure why...I tried many a proc to try and fix it but just resorted to having him respawn

**Comment by Trilbyspaceclone** [comment]
Has been fixed in #5747
