### ISSUE TITLE
Artist Rifle-caliber Revolvers seem to only roll same stuff

### ISSUE THREAD

**Issue by PvtStupidhead** [sojourn-13/sojourn-station#5583]
As title says, I've seen mostly 1.4 DMG / 1 AP rolls with 1 Fire Delay constantly on my rifle weaponry.

![image](https://github.com/user-attachments/assets/92f3ae41-28cd-482e-9b4a-c9f2a77ea0a9)

8.6mm.

![image](https://github.com/user-attachments/assets/0e61644f-7e56-4b02-9553-ffc2ee485b52)

7.62mm

As you can see in these two examples, sure, only two but I remember doing one earlier a few shifts ago and saw the same thing there. Hard to test really without good vigilance oddity, so dunno for sure.

**Comment by Trilbyspaceclone** [comment]
Was determed to just be insainly constant luck.
