### ISSUE TITLE
The new bluecross weapons finds cannot be used with the 'Random Mechanics' boxes from prospectors

### ISSUE THREAD

**Issue by PvtStupidhead** [sojourn-13/sojourn-station#5630]
As the title reads, you cannot get the Bluecross weapons anymore from the random mechancis boxes, as they just spawn an empty box that says it's got something in it, but you cannot remove the bluerift from it.

![image](https://github.com/user-attachments/assets/ed2540dc-b73e-4ec0-a11e-538d79f72808)

**Comment by Trilbyspaceclone** [comment]
Should now be fixed, woops
