### ISSUE TITLE
Juggernaut suit's helmet causes 'UNNAMED' black dots to appear that interfere with your clicking ability

### ISSUE THREAD

**Issue by PvtStupidhead** [sojourn-13/sojourn-station#5639]
As the title says, these black dots normally reserved for limiting vision with welding masks or such appear, but they are actually clickable. If you try to click them or any item underneath them while in helping mode, you will not be able to click them and must instead dodge around them to get to items in your inventory and such.

![image](https://github.com/user-attachments/assets/74a263d6-66a0-402a-930b-3e5eca548079)

**Comment by Trilbyspaceclone** [comment]
This is actually indented, those are added to make sniping with the suit harder as they are given by the tint level
