### ISSUE TITLE
Some mapping issues.

### ISSUE THREAD

**Issue by 1yakynm** [sojourn-13/sojourn-station#5666]
Soteria Outpost, and the Lower level of Soteria Upper (I.E) where the genetics and Xenobiology is don't have any firelockers and Oxygen lockers in the hallways.

Additionally, Dormitories have no cameras whatsoever past the Artist's workshop. Which isn't a problem to anyone else **BUT** the AI. Considering that it's core is positioned right under this space (Screenshot provided, Red Square) between Room 4 and Room 3, meaning that anyone with basic access to the colony could weld through, remove the floor and chuck down an EMP grenade. Or worse - get in, card it, build a table and get out through the hole they made.
![image](https://github.com/user-attachments/assets/c3ceac47-3f71-48ab-bda9-ae123e6c1576)

**Comment by Trilbyspaceclone** [comment]
You cant make open space via welding down. But can add the camera and fire/o2 lockers
