### ISSUE TITLE
Fireman's throw in window

### ISSUE THREAD

**Issue by du-top** [sojourn-13/sojourn-station#5739]
The fireman's throw (weird name?) / shoulder throw is grabbing someone else aggressively and clicking yourself. This throws the target over the attacker's shoulder (behind them). It checks for walls, but not windows. Therefore it's possible that the target is inside of that window. This bug can be abused and is actively being abused. (At least at the point in time where I noted it down, but I didn't see any changes since then regarding that).

The line https://github.com/sojourn-13/sojourn-station/blob/31382195a0cb8609d156bc8d288a758c59b169bd/code/modules/mob/mob_grab_specials.dm#L270 checks whether the target tile is a wall (/turf/simulated/wall), but a window is not a wall. I don't see the connection between turf and a window on it, so I don't know what to put there.

**Comment by Trilbyspaceclone** [comment]
Thank you for quoting the line
