### ISSUE TITLE
Carthatoline does not give CE_antitox 3

### ISSUE THREAD

**Issue by Looking4bros** [sojourn-13/sojourn-station#5821]
By the looks of the comment on the plasma poisoning internal wound here https://github.com/sojourn-13/sojourn-station/blob/2965c2b28c956f7a8aa4afc3095ef761ec21824a/code/modules/organs/internal/internal_wounds/organic.dm#L177-L179
it's implied that Carthatoline is the cure for plasma poisoning, however when you look at it's chemical effects, and how the add_chemical_effect proc works

https://github.com/sojourn-13/sojourn-station/blob/7816f4c48395e9b53a3ed37d5c7f5ec0242fe04a/code/modules/reagents/reagents/medicine.dm#L268

https://github.com/sojourn-13/sojourn-station/blob/2965c2b28c956f7a8aa4afc3095ef761ec21824a/code/modules/mob/living/carbon/carbon.dm#L353-L362

It will only be giving a Antitox effect of 0.6, as only 0.2 carthatoline will be removed with it's metabolization.

I suggest removing the " * removed" if Carthatoline having an antitox of 3 is intended.

**Comment by Trilbyspaceclone** [comment]
This should be fixed by #5836
